# Generated by Django 5.2 on 2026-04-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('duracion_anos', models.PositiveSmallIntegerField(verbose_name='Duración (años)')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MateriaEnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre'), (3, 'Anual')], verbose_name='Cuatrimestre')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_planes', to='planes.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia en Plan',
                'verbose_name_plural': 'Materias en Plan',
                'ordering': ['ano', 'cuatrimestre', 'materia__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de plan')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Versión')),
                ('version_id', models.PositiveIntegerField(verbose_name='Version ID')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='planes.carrera', verbose_name='Carrera')),
                ('materias', models.ManyToManyField(related_name='planes', through='planes.MateriaEnPlan', to='planes.materia', verbose_name='Materias')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['carrera', 'codigo'],
                'unique_together': {('carrera', 'codigo', 'version')},
            },
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_en_plan', to='planes.planestudio', verbose_name='Plan de estudio'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaenplan',
            unique_together={('materia', 'plan')},
        ),
    ]
