# Generated by Django 5.2 on 2026-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaenplan',
            name='hs_totales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas totales'),
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='nombre',
            field=models.CharField(blank=True, help_text='Si está vacío se usa el nombre de la materia.', max_length=250, verbose_name='Nombre en el plan'),
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='tope_hs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Límite de horas para esta materia. Opcional.', null=True, verbose_name='Tope de horas'),
        ),
    ]
