# Generated by Django 5.2 on 2026-04-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_materiaenplan_campos_academicos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planestudio',
            unique_together={('carrera', 'codigo')},
        ),
        migrations.RemoveField(
            model_name='planestudio',
            name='version',
        ),
        migrations.RemoveField(
            model_name='planestudio',
            name='version_id',
        ),
    ]
