# Generated by Django 5.2 on 2026-04-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_quitar_version_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaenplan',
            name='es_optativa',
            field=models.BooleanField(default=False, verbose_name='Es optativa'),
        ),
    ]
