# Generated by Django 5.2 on 2026-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0010_carrera_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='es_servicio',
            field=models.BooleanField(default=False, verbose_name='Materia de servicio'),
        ),
    ]
