# Generated by Django 5.2 on 2026-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0011_materia_es_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='es_servicio',
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='es_servicio',
            field=models.BooleanField(default=False, verbose_name='Materia de servicio'),
        ),
    ]
