# Generated by Django 5.2 on 2026-05-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0012_materiaenplan_es_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaenplan',
            name='departamento_dictante',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería')], help_text='Obligatorio cuando es materia de servicio.', max_length=50, verbose_name='Departamento que la dicta'),
        ),
    ]
