# Generated by Django 5.2 on 2026-05-02 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0013_materiaenplan_departamento_dictante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('fecha_hora_propuesta', models.DateTimeField(blank=True, null=True, verbose_name='Día y hora propuesto')),
                ('permite_libres_propuesto', models.BooleanField(default=True, verbose_name='Pueden rendir libres (propuesto)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del director')),
                ('respuesta_admin', models.TextField(blank=True, verbose_name='Respuesta del administrador')),
                ('presidente_propuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sol_como_presidente', to='planes.docente', verbose_name='Presidente propuesto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_tribunal', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='planes.tribunalexaminador', verbose_name='Tribunal')),
                ('vocal_1_propuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sol_como_vocal_1', to='planes.docente', verbose_name='1er. Vocal propuesto')),
                ('vocal_2_propuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sol_como_vocal_2', to='planes.docente', verbose_name='2do. Vocal propuesto')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de tribunal',
                'verbose_name_plural': 'Solicitudes de cambio de tribunal',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
