# Generated by Django 5.2 on 2026-05-02 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0014_solicitudcambiotribunal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalexaminador',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribunales_como_presidente', to='planes.docente', verbose_name='Presidente'),
        ),
        migrations.AlterField(
            model_name='tribunalexaminador',
            name='vocal_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribunales_como_vocal_1', to='planes.docente', verbose_name='1er. Vocal'),
        ),
        migrations.AlterField(
            model_name='tribunalexaminador',
            name='vocal_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribunales_como_vocal_2', to='planes.docente', verbose_name='2do. Vocal'),
        ),
    ]
