# Generated by Django 5.2 on 2026-05-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0019_solicitud_valores_anteriores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='dia_semana_propuesto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')], null=True, verbose_name='Día de la semana nuevo'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='hora_propuesta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora nueva'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='permite_libres_propuesto',
            field=models.BooleanField(default=True, verbose_name='Modalidad nueva'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='presidente_propuesto_dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='Presidente nuevo (DNI)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='presidente_propuesto_nombre',
            field=models.CharField(blank=True, max_length=250, verbose_name='Presidente nuevo (nombre)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='vocal_1_propuesto_dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='1er. Vocal nuevo (DNI)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='vocal_1_propuesto_nombre',
            field=models.CharField(blank=True, max_length=250, verbose_name='1er. Vocal nuevo (nombre)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='vocal_2_propuesto_dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='2do. Vocal nuevo (DNI)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='vocal_2_propuesto_nombre',
            field=models.CharField(blank=True, max_length=250, verbose_name='2do. Vocal nuevo (nombre)'),
        ),
    ]
