# Generated by Django 5.2 on 2026-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0021_tribunaladmin_pendiente_sincronizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribunalexaminador',
            options={'verbose_name': 'Tribunal Examinador (Director)', 'verbose_name_plural': 'Tribunales Examinadores (Director)'},
        ),
        migrations.AlterField(
            model_name='tribunaladmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
