# Generated by Django 5.2 on 2026-05-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0023_solicitudinformetribunal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTribunalesEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería')], max_length=50, verbose_name='Departamento')),
                ('fecha_envio', models.DateTimeField(verbose_name='Fecha de envío')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_tribunales_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Director')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_enviados', to='planes.solicitudinformetribunal', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Informe de tribunales enviado',
                'verbose_name_plural': 'Informes de tribunales enviados',
                'ordering': ['-fecha_envio'],
                'unique_together': {('solicitud', 'departamento')},
            },
        ),
    ]
