# Generated by Django 5.2 on 2026-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0025_rebuild_solicitudcambiotribunal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
