# Generated by Django 5.2 on 2026-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0026_alter_solicitudcambiotribunal_id'),
        ('planes', '0026_refactor_tribunal_solicitud'),
    ]

    operations = [
    ]
