# Generated by Django 5.2 on 2026-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0027_merge_20260503_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambioitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
