# Generated by Django 5.2 on 2026-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0028_alter_solicitudcambioitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambioitem',
            name='snapshot_tribunal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
