# Generated by Django 5.2 on 2026-05-03 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0029_snapshot_tribunal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_solicitante', models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería')], max_length=50, verbose_name='Departamento solicitante')),
                ('departamento_dictante', models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería')], max_length=50, verbose_name='Departamento dictante')),
                ('anio_academico', models.PositiveSmallIntegerField(verbose_name='Año académico')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_servicio', to=settings.AUTH_USER_MODEL, verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Solicitud de servicio',
                'verbose_name_plural': 'Solicitudes de servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_totales', models.PositiveSmallIntegerField(verbose_name='Horas totales')),
                ('materia_en_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_servicio_items', to='planes.materiaenplan', verbose_name='Materia en plan')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planes.solicitudservicio', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Item de solicitud de servicio',
                'verbose_name_plural': 'Items de solicitud de servicio',
                'unique_together': {('solicitud', 'materia_en_plan')},
            },
        ),
    ]
