# Generated by Django 5.2 on 2026-05-03 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0030_solicitud_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocatoriaSolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1° Cuatrimestre + Anuales'), (2, '2° Cuatrimestre')], verbose_name='Cuatrimestre')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('directores_notificados', models.PositiveSmallIntegerField(default=0, verbose_name='Directores notificados')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias_servicio', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Convocatoria de solicitud de servicio',
                'verbose_name_plural': 'Convocatorias de solicitud de servicio',
                'ordering': ['-anio', '-cuatrimestre'],
                'unique_together': {('cuatrimestre', 'anio')},
            },
        ),
    ]
