# Generated by Django 5.2 on 2026-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0032_dictante_externo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='departamento',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='informetribunalesenviado',
            name='departamento',
            field=models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='departamento',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='materiaenplan',
            name='departamento_dictante',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], help_text='Obligatorio cuando es materia de servicio.', max_length=50, verbose_name='Departamento que la dicta'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiotribunal',
            name='departamento',
            field=models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='departamento_dictante',
            field=models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento dictante'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='departamento_solicitante',
            field=models.CharField(choices=[('', '---------'), ('Matemática', 'Matemática'), ('Física', 'Física'), ('Geología', 'Geología'), ('Electrónica', 'Electrónica'), ('Informática', 'Informática'), ('Minería', 'Minería'), ('Externo', 'Externo')], max_length=50, verbose_name='Departamento solicitante'),
        ),
    ]
