# Generated by Django 4.2.30 on 2026-04-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('fecha_inicio_1c', models.DateField(verbose_name='Inicio 1° Cuatrimestre')),
                ('fecha_fin_1c', models.DateField(verbose_name='Fin 1° Cuatrimestre')),
                ('fecha_inicio_2c', models.DateField(verbose_name='Inicio 2° Cuatrimestre')),
                ('fecha_fin_2c', models.DateField(verbose_name='Fin 2° Cuatrimestre')),
                ('semanas_cuatrimestre', models.PositiveIntegerField(default=15, verbose_name='Semanas por cuatrimestre')),
                ('semanas_anual', models.PositiveIntegerField(default=30, verbose_name='Semanas anuales')),
            ],
            options={
                'verbose_name': 'Calendario Académico',
                'verbose_name_plural': 'Calendarios Académicos',
                'ordering': ['-anno'],
            },
        ),
    ]
