# Generated by Django 4.2.30 on 2026-04-14 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProtocolizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comentarios_revision', models.TextField(blank=True, help_text='Observaciones del revisor.', verbose_name='Comentarios de revisión')),
                ('nombre_curso', models.CharField(max_length=200, verbose_name='Nombre / Materia')),
                ('carrera', models.CharField(blank=True, max_length=200, verbose_name='Carrera')),
                ('plan_estudio', models.CharField(blank=True, max_length=50, verbose_name='Plan')),
                ('anno_carrera', models.CharField(blank=True, max_length=10, verbose_name='Año en la carrera')),
                ('periodo', models.CharField(blank=True, choices=[('1c', '1° Cuatrimestre'), ('2c', '2° Cuatrimestre'), ('anual', 'Anual')], max_length=10, verbose_name='Período')),
                ('hs_teoricas', models.PositiveIntegerField(default=0, verbose_name='Hs. Teóricas')),
                ('hs_practicas_aula', models.PositiveIntegerField(default=0, verbose_name='Hs. Prácticas de Aula')),
                ('hs_lab_campo', models.PositiveIntegerField(default=0, verbose_name='Hs. Práct. Lab/Campo')),
                ('tipificacion', models.CharField(blank=True, choices=[('obligatoria', 'Obligatoria'), ('optativa', 'Optativa'), ('electiva', 'Electiva'), ('extracurricular', 'Extracurricular')], max_length=20, verbose_name='Tipificación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('cantidad_semanas', models.PositiveIntegerField(default=0, verbose_name='Semanas')),
                ('fundamentacion', models.TextField(verbose_name='Fundamentación')),
                ('objetivos', models.TextField(verbose_name='Objetivos / Resultados de Aprendizaje')),
                ('contenidos_minimos', models.TextField(blank=True, help_text='Síntesis de los contenidos mínimos según el Plan de Estudios.', verbose_name='Contenidos Mínimos')),
                ('unidades', models.TextField(help_text='Descripción de cada unidad (I, II, III…). Una unidad por línea o separadas por doble salto.', verbose_name='Unidades temáticas')),
                ('plan_trabajos_practicos', models.TextField(blank=True, verbose_name='Plan de Trabajos Prácticos')),
                ('regimen_aprobacion', models.TextField(verbose_name='Régimen de Aprobación')),
                ('bibliografia_basica', models.TextField(verbose_name='Bibliografía Básica')),
                ('bibliografia_complementaria', models.TextField(blank=True, verbose_name='Bibliografía Complementaria')),
                ('resumen_objetivos', models.TextField(blank=True, verbose_name='Resumen de Objetivos')),
                ('resumen_programa', models.TextField(blank=True, verbose_name='Resumen del Programa')),
                ('imprevistos', models.TextField(blank=True, verbose_name='Imprevistos')),
                ('contacto_otros', models.TextField(blank=True, verbose_name='Otros / Datos de contacto')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Solicitud de Protocolización',
                'verbose_name_plural': 'Solicitudes de Protocolización',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Apellido y Nombre')),
                ('funcion', models.CharField(choices=[('responsable', 'Responsable'), ('colaborador', 'Colaborador'), ('auxiliar', 'Auxiliar'), ('adscripto', 'Adscripto')], max_length=20, verbose_name='Función')),
                ('cargo', models.CharField(blank=True, choices=[('titular', 'Titular'), ('asociado', 'Asociado'), ('adjunto', 'Adjunto'), ('jtp', 'J.T.P.'), ('ay1', 'Ayudante de 1ra'), ('ay2', 'Ayudante de 2da'), ('otro', 'Otro')], max_length=20, verbose_name='Cargo')),
                ('dedicacion', models.CharField(blank=True, choices=[('exclusiva', 'Exclusiva'), ('semi_exclusiva', 'Semi-exclusiva'), ('simple', 'Simple')], max_length=20, verbose_name='Dedicación')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_docente', to='solicitudes.solicitudprotocolizacion')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo Docente',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
