# Generated by Django 4.2.30 on 2026-04-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='area',
            field=models.CharField(blank=True, max_length=200, verbose_name='Área'),
        ),
    ]
