# Generated by Django 4.2.30 on 2026-04-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitudprotocolizacion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroequipodocente',
            name='dedicacion',
            field=models.CharField(blank=True, choices=[('10hs', '10 Hs'), ('20hs', '20 Hs'), ('40hs', '40 Hs')], max_length=20, verbose_name='Dedicación'),
        ),
    ]
