# Generated by Django 5.2 on 2026-04-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_miembroequipodocente_dedicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='departamento_docente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='email_docente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='legajo_docente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Legajo'),
        ),
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='nombre_docente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
    ]
