# Generated by Django 4.2.30 on 2026-04-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitudprotocolizacion_departamento_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='tipificacion',
            field=models.CharField(blank=True, choices=[('optativa', 'Optativa'), ('electiva', 'Electiva'), ('extracurricular', 'Extracurricular')], max_length=20, verbose_name='Tipificación'),
        ),
    ]
