# Generated by Django 5.2 on 2026-04-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
        ('solicitudes', '0005_alter_solicitudprotocolizacion_tipificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.carrera', verbose_name='Carrera'),
        ),
    ]
