# Generated by Django 5.2 on 2026-04-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_quitar_version_plan'),
        ('solicitudes', '0006_carrera_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='plan_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.planestudio', verbose_name='Plan de estudio'),
        ),
    ]
