# Generated by Django 5.2 on 2026-04-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_materiaenplan_es_optativa'),
        ('solicitudes', '0007_plan_estudio_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='optativa_vinculada',
            field=models.ForeignKey(blank=True, help_text='Optativa del plan a la que corresponde esta protocolización.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.materiaenplan', verbose_name='Optativa vinculada'),
        ),
    ]
