# Generated by Django 5.2 on 2026-04-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_optativa_vinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='modalidad_cursado',
            field=models.CharField(blank=True, choices=[('teo_aula_campo', 'Teoría con Prácticas de Aula y Campo'), ('teo_aula_lab', 'Teoría con Prácticas de Aula y Laboratorios'), ('teo_aula', 'Teoría con Prácticas de Aula'), ('teo_aula_lab_campo', 'Teoría con Prácticas de Aula, Laboratorio y Campo')], max_length=20, verbose_name='Modalidad de cursado'),
        ),
    ]
