# Generated by Django 5.2 on 2026-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_modalidad_cursado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='condicion',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('libre', 'Libre'), ('promocional', 'Promocional')], max_length=20, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='numero_comision',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de comisión'),
        ),
    ]
