# Generated by Django 5.2 on 2026-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_add_comision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipodocente',
            name='rol_comision',
            field=models.CharField(blank=True, choices=[('prof_responsable', 'Prof. Responsable'), ('prof_colaborador', 'Prof. Colaborador'), ('resp_practico', 'Responsable de Práctico'), ('aux_practico', 'Auxiliar de Práctico'), ('aux_laboratorio', 'Auxiliar de Laboratorio')], help_text='Categoría que ocupa en la comisión para el sistema de alumnos.', max_length=20, verbose_name='Rol en comisión'),
        ),
    ]
