# Generated by Django 5.2 on 2026-04-21 18:49

from django.db import migrations, models


_FUNCION_MAP = {
    'responsable': 'prof_responsable',
    'colaborador': 'prof_colaborador',
    'auxiliar':    'aux_practico',
    'adscripto':   'aux_laboratorio',
}


def convertir_funcion(apps, schema_editor):
    MiembroEquipoDocente = apps.get_model('solicitudes', 'MiembroEquipoDocente')
    for m in MiembroEquipoDocente.objects.all():
        nuevo = _FUNCION_MAP.get(m.funcion) or m.funcion
        if nuevo != m.funcion:
            m.funcion = nuevo
            m.save(update_fields=['funcion'])


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_add_rol_comision_to_miembro'),
    ]

    operations = [
        migrations.RunPython(convertir_funcion, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='miembroequipodocente',
            name='rol_comision',
        ),
        migrations.AlterField(
            model_name='miembroequipodocente',
            name='funcion',
            field=models.CharField(choices=[('prof_responsable', 'Prof. Responsable'), ('prof_colaborador', 'Prof. Colaborador'), ('resp_practico', 'Responsable de Práctico'), ('aux_practico', 'Auxiliar de Práctico'), ('aux_laboratorio', 'Auxiliar de Laboratorio')], max_length=20, verbose_name='Función'),
        ),
    ]
