# Generated by Django 5.2 on 2026-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_merge_funcion_rol_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='hs_teorico_practico',
            field=models.PositiveIntegerField(default=0, verbose_name='Hs. Teórico/Práctico'),
        ),
    ]
