# Generated by Django 5.2 on 2026-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_add_hs_teorico_practico'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipodocente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI'),
        ),
    ]
