# Generated by Django 5.2 on 2026-04-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_add_codigo_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='condicion',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('promocional', 'Promocional')], max_length=20, verbose_name='Condición de aprobación'),
        ),
    ]
