# Generated by Django 5.2 on 2026-04-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_materiaenplan_es_optativa'),
        ('solicitudes', '0016_alter_solicitudprotocolizacion_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('aprobada', 'Aprobada'), ('regularizada', 'Regularizada')], max_length=15, verbose_name='Condición')),
                ('tipo', models.CharField(choices=[('cursar', 'Para cursar'), ('rendir', 'Para rendir')], max_length=10, verbose_name='Tipo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.materia', verbose_name='Materia')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas', to='solicitudes.solicitudprotocolizacion')),
            ],
            options={
                'verbose_name': 'Correlativa Requerida',
                'verbose_name_plural': 'Correlativas Requeridas',
                'ordering': ['tipo', 'materia__nombre'],
            },
        ),
    ]
