# Generated by Django 5.2 on 2026-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_add_correlativa_requerida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='tipificacion',
            field=models.CharField(blank=True, choices=[('optativa', 'Optativa'), ('taller', 'Taller'), ('curso', 'Curso'), ('jornada', 'Jornada'), ('congreso', 'Congreso')], max_length=20, verbose_name='Tipificación'),
        ),
    ]
