# Generated by Django 5.2 on 2026-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_split_tipificacion_extracurricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='acta_comision_carrera',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/actas/', verbose_name='Acta Comisión de Carrera'),
        ),
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='acta_consejo_departamental',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/actas/', verbose_name='Acta Consejo Departamental'),
        ),
    ]
