# Generated by Django 5.2 on 2026-04-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_add_actas_aval'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprotocolizacion',
            name='numero_resolucion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de resolución'),
        ),
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Con Observaciones'), ('elevada', 'Elevada al Admin'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
