# Generated by Django 5.2 on 2026-04-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_solicitudprotocolizacion_numero_resolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Con Observaciones'), ('devuelta', 'Devuelta al Docente'), ('elevada', 'Elevada al Admin'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
