# Generated by Django 5.2 on 2026-04-23 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0021_alter_solicitudprotocolizacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(blank=True, max_length=200, verbose_name='Nombre y apellido')),
                ('legajo_docente', models.CharField(blank=True, max_length=20, verbose_name='Legajo')),
                ('departamento_docente', models.CharField(blank=True, max_length=150, verbose_name='Departamento')),
                ('email_docente', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Con Observaciones'), ('devuelta', 'Devuelta al Docente'), ('elevada', 'Elevada al Admin'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comentarios_revision', models.TextField(blank=True, help_text='Observaciones del revisor.', verbose_name='Comentarios de revisión')),
                ('denominacion_curso', models.CharField(max_length=200, verbose_name='Denominación del curso')),
                ('responsable_nombre', models.CharField(max_length=200, verbose_name='Responsable')),
                ('responsable_titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('responsable_documento', models.CharField(blank=True, max_length=20, verbose_name='N° Documento')),
                ('responsable_institucion', models.CharField(blank=True, max_length=200, verbose_name='Institución de origen')),
                ('responsable_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('responsable_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('co_responsable_nombre', models.CharField(blank=True, max_length=200, verbose_name='Co-responsable')),
                ('co_responsable_titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('co_responsable_documento', models.CharField(blank=True, max_length=20, verbose_name='N° Documento')),
                ('co_responsable_fax', models.CharField(blank=True, max_length=50, verbose_name='FAX')),
                ('co_responsable_institucion', models.CharField(blank=True, max_length=200, verbose_name='Institución de origen')),
                ('co_responsable_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('colaborador', models.CharField(blank=True, max_length=300, verbose_name='Colaborador')),
                ('auxiliar', models.CharField(blank=True, max_length=300, verbose_name='Auxiliar')),
                ('coordinador', models.CharField(max_length=200, verbose_name='Coordinador')),
                ('credito_horario_total', models.PositiveIntegerField(default=0, verbose_name='Crédito horario total (hs)')),
                ('destinatarios', models.TextField(verbose_name='Destinatarios')),
                ('cupo', models.PositiveIntegerField(default=0, verbose_name='Cupo')),
                ('calendario_actividades', models.TextField(blank=True, verbose_name='Calendario de actividades')),
                ('fecha_elevar_nomina', models.DateField(blank=True, null=True, verbose_name='Fecha prevista para elevar la nómina de alumnos aprobados')),
                ('objetivos', models.TextField(verbose_name='Objetivos')),
                ('contenidos_minimos', models.TextField(verbose_name='Contenidos mínimos')),
                ('programa', models.TextField(verbose_name='Programa')),
                ('sistema_evaluacion', models.TextField(verbose_name='Sistema de evaluación')),
                ('bibliografia', models.TextField(verbose_name='Bibliografía')),
                ('costos_financiamiento', models.TextField(blank=True, verbose_name='Costos y fuentes de financiamiento')),
                ('acta_consejo_departamental', models.FileField(blank=True, null=True, upload_to='talleres/actas/', verbose_name='Acta Consejo Departamental')),
                ('numero_resolucion', models.CharField(blank=True, max_length=50, verbose_name='Número de resolución')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Solicitud de Taller',
                'verbose_name_plural': 'Solicitudes de Taller',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
    ]
