# Generated by Django 5.2 on 2026-04-23 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0022_solicitudtaller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='auxiliar',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_documento',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_email',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_fax',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_institucion',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='co_responsable_titulo',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_documento',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_email',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_institucion',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_telefono',
        ),
        migrations.RemoveField(
            model_name='solicitudtaller',
            name='responsable_titulo',
        ),
        migrations.CreateModel(
            name='MiembroEquipoTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('responsable', 'Responsable'), ('co_responsable', 'Co-responsable'), ('coordinador', 'Coordinador'), ('colaborador', 'Colaborador'), ('auxiliar', 'Auxiliar')], max_length=20, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='N° Documento')),
                ('institucion', models.CharField(blank=True, max_length=200, verbose_name='Institución de origen')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono / FAX')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='solicitudes.solicitudtaller')),
            ],
            options={
                'verbose_name': 'Miembro del equipo (Taller)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
