# Generated by Django 5.2 on 2026-04-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0023_remove_solicitudtaller_auxiliar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroequipotaller',
            name='rol',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('responsable_coordinador', 'Responsable y Coordinador'), ('co_responsable', 'Co-responsable'), ('coordinador', 'Coordinador'), ('colaborador', 'Colaborador'), ('auxiliar', 'Auxiliar')], max_length=30, verbose_name='Rol'),
        ),
    ]
