# Generated by Django 5.2 on 2026-05-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0024_alter_miembroequipotaller_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtaller',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Curso/Taller', 'verbose_name_plural': 'Solicitudes de Curso/Taller'},
        ),
        migrations.AlterField(
            model_name='solicitudprotocolizacion',
            name='tipificacion',
            field=models.CharField(blank=True, choices=[('optativa', 'Optativa'), ('jornada', 'Jornada'), ('congreso', 'Congreso')], max_length=20, verbose_name='Tipificación'),
        ),
    ]
