# Generated by Django 4.2.30 on 2026-04-14 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comentarios_revision', models.TextField(blank=True, help_text='Observaciones del revisor.', verbose_name='Comentarios de revisión')),
                ('anno', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=4, verbose_name='Año')),
                ('fecha_desde', models.DateField(verbose_name='Período desde')),
                ('fecha_hasta', models.DateField(verbose_name='Período hasta')),
                ('cargo', models.CharField(choices=[('PAD', 'Profesor Adjunto (PAD)'), ('PAS', 'Profesor Asociado (PAS)'), ('PTI', 'Profesor Titular (PTI)'), ('JTP', 'Jefe de Trabajos Prácticos (JTP)'), ('AY1', 'Ayudante de Primera (AY1)'), ('AY2', 'Ayudante de Segunda (AY2)')], max_length=10, verbose_name='Cargo')),
                ('dedicacion', models.CharField(choices=[('exclusiva', 'Exclusiva'), ('semi_exclusiva', 'Semi Exclusiva'), ('simple', 'Simple')], max_length=20, verbose_name='Dedicación')),
                ('designacion', models.CharField(choices=[('efectivo', 'Efectivo'), ('interino', 'Interino'), ('contratado', 'Contratado')], max_length=20, verbose_name='Designación')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='Área')),
                ('a1_descripcion', models.TextField(help_text='Actividades curriculares de grado y pregrado (asignaturas de carreras).', verbose_name='A.1 — Descripción')),
                ('a1_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('a1_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('a2_descripcion', models.TextField(blank=True, help_text='Cursos extracurriculares.', verbose_name='A.2 — Descripción')),
                ('a2_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('a2_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('a3_descripcion', models.TextField(blank=True, help_text='Tareas de posgrado.', verbose_name='A.3 — Descripción')),
                ('a3_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('a3_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('a4_descripcion', models.TextField(blank=True, help_text='Formación de recursos humanos.', verbose_name='A.4 — Descripción')),
                ('a4_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('a4_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('b_descripcion', models.TextField(blank=True, help_text='Investigación.', verbose_name='B — Descripción')),
                ('b_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('b_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('c_descripcion', models.TextField(blank=True, help_text='Transferencias o servicios.', verbose_name='C — Descripción')),
                ('c_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('c_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('d_descripcion', models.TextField(blank=True, help_text='Extensión universitaria.', verbose_name='D — Descripción')),
                ('d_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('d_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('e_descripcion', models.TextField(blank=True, help_text='Perfeccionamiento.', verbose_name='E — Descripción')),
                ('e_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('e_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('f_descripcion', models.TextField(blank=True, help_text='Gobierno y gestión.', verbose_name='F — Descripción')),
                ('f_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('f_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('g_descripcion', models.TextField(blank=True, help_text='Otros.', verbose_name='G — Descripción')),
                ('g_hs_1c', models.PositiveIntegerField(default=0, verbose_name='Hs 1º Cuat.')),
                ('g_hs_2c', models.PositiveIntegerField(default=0, verbose_name='Hs 2º Cuat.')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Planificación de Actividades',
                'verbose_name_plural': 'Planificaciones de Actividades',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
                'unique_together': {('usuario', 'anno')},
            },
        ),
    ]
