# Generated by Django 5.2 on 2026-04-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0002_planificacionactividades_departamento_docente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacionactividades',
            unique_together=set(),
        ),
    ]
