# Generated by Django 5.2 on 2026-04-05 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeActividadAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comentarios_revision', models.TextField(blank=True, help_text='Observaciones del revisor.', verbose_name='Comentarios de revisión')),
                ('anno_academico', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=4, verbose_name='Año académico')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría docente')),
                ('dedicacion', models.CharField(choices=[('exclusiva', 'Dedicación Exclusiva'), ('semi_exclusiva', 'Semi Exclusiva'), ('simple', 'Dedicación Simple')], max_length=50, verbose_name='Dedicación')),
                ('materias_dictadas', models.TextField(help_text='Listá cada materia con carrera, año y carga horaria.', verbose_name='Materias / Asignaturas dictadas')),
                ('carga_horaria_docencia', models.PositiveIntegerField(verbose_name='Carga horaria total de docencia (hs/semana)')),
                ('actividades_investigacion', models.TextField(blank=True, help_text='Proyectos, publicaciones, dirección de tesis, etc.', verbose_name='Actividades de investigación')),
                ('actividades_extension', models.TextField(blank=True, help_text='Proyectos de extensión, vinculación con la comunidad, etc.', verbose_name='Actividades de extensión')),
                ('actividades_gestion', models.TextField(blank=True, help_text='Cargos de gestión, comisiones, etc.', verbose_name='Actividades de gestión')),
                ('actividades_formacion', models.TextField(blank=True, help_text='Cursos, posgrados, congresos asistidos, etc.', verbose_name='Formación y capacitación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Informe de Actividad Anual',
                'verbose_name_plural': 'Informes de Actividad Anual',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
                'unique_together': {('usuario', 'anno_academico')},
            },
        ),
    ]
