# Generated by Django 5.2 on 2026-04-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_informeactividadanual_departamento_docente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informeactividadanual',
            unique_together=set(),
        ),
    ]
