# Generated by Django 5.2 on 2026-04-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_alter_informeactividadanual_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeactividadanual',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Con Observaciones'), ('elevada', 'Elevada al Admin'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
